/**
 * Generates src/i18n/locales/{ja,en}.ts from the extracted catalog plus the
 * translation sources:
 *   tools/translations/*.json     — Korean source key  -> [japanese, english]
 *   tools/translations/from-english/*.json  — English source key -> [japanese, null]
 *
 * A key whose source language already matches the target locale needs no entry:
 * t() falls back to the key itself.
 */
import fs from 'fs';
import path from 'path';

const catalog = JSON.parse(fs.readFileSync('tools/generated/i18n-catalog.json', 'utf8'));

const load = dir => {
  const out = {};
  if (!fs.existsSync(dir)) return out;
  for (const f of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (!f.isFile() || !f.name.endsWith('.json') || f.name === 'ignore.json') continue;
    Object.assign(out, JSON.parse(fs.readFileSync(path.join(dir, f.name), 'utf8')));
  }
  return out;
};
const fromKo = load('tools/translations');
const fromEn = load('tools/translations/from-english');

const lit = s => JSON.stringify(s);

const build = (locale, title) => {
  const lines = [
    '/**',
    ' * @license',
    ' * SPDX-License-Identifier: Apache-2.0',
    ' *',
    ' * GENERATED by tools/i18n-build.mjs — edit the JSON sources under tools/translations/ instead.',
    ' */',
    '',
    "import type { Catalog } from '../types';",
    '',
    `/** ${title} Keys are the original source strings (Korean, or English where the UI was authored in English). */`,
    `export const ${locale}: Catalog = {`,
  ];
  let currentFile = null;
  let count = 0;
  for (const entry of catalog) {
    const table = entry.lang === 'ko' ? fromKo : fromEn;
    const value = table[entry.key]?.[locale === 'ja' ? 0 : 1];
    if (value === undefined || value === null || value === entry.key) continue;
    if (entry.files[0] !== currentFile) {
      currentFile = entry.files[0];
      lines.push(`  // ── ${currentFile} ${'─'.repeat(Math.max(2, 58 - currentFile.length))}`);
    }
    lines.push(`  ${lit(entry.key)}: ${lit(value)},`);
    count++;
  }
  lines.push('};', '');
  fs.writeFileSync(`src/i18n/locales/${locale}.ts`, lines.join('\n'));

  const need = catalog.filter(e => e.lang !== locale).length;
  console.log(`src/i18n/locales/${locale}.ts: ${count}/${need} translated`);
};

build('ja', 'Japanese catalog.');
build('en', 'English catalog.');
